// thanks chatGPT   go smoothly between a and b value in t time
function lerp(a, b, t) {
    return (1 - t) * a + t * b;
}

// to not do a 360 when it goes to -1/2Pi to 2PI, complicated math generated by chatGPT it's fantastic, some explanation below
function normalizeAngle(angle) {
    return angle - Math.floor((angle + Math.PI) / (2 * Math.PI)) * (2 * Math.PI);
  }
function lerpAngle(a, b, t) {
    const pi2 = Math.PI * 2;
    const da = normalizeAngle(b - a);
    return normalizeAngle(a + da * t);
}

// get a random integer between min and max-1
function getRandomBetween(min, max) {
    return Math.random() * (max - min) + min;
}

export {lerp, lerpAngle, getRandomBetween}


/*Here, a and b are the two angles you want to interpolate between, and t is a value between 0 and 1 that determines the interpolation amount.
The function returns the interpolated angle value between a and b.

The implementation takes advantage of the fact that adding or subtracting a multiple of 2π to an angle doesn't change its value.
It first computes the difference diff between a and b, adding 2π to ensure that the result is positive,
and then subtracting π to shift the range from [0, 2π) to [-π, π).
The result is then interpolated by t, and finally wrapped back into the range [-π, π) by adding 2π and taking the modulo operator.
    
   By ChatGPT for lerpAngle */
